name: 'montreal_methane'
version: '1.0.0'
config-version: 2

profile: 'montreal_methane'

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  montreal_methane:
    +materialized: table